version: "3.3"
volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/labs/lab11"
services:
  spark-master:
    image: nstanger/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_HOSTNAME=spark-master"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_MEMORY=2g"
    volumes:
      - data:/mnt/data
    command: "start-master.sh"
  spark-worker:
    image: nstanger/spark:latest
    depends_on:
      - spark-master
    ports:
      - "8080"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
      - "SPARKMONITOR_UI_PORT=8080"
      - "SPARK_WORKER_MEMORY=2g"
    volumes:
      - data:/mnt/data
    command: "start-worker.sh"
  pyspark:
    image: nstanger/pyspark:latest
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell"
    volumes:
      - data:/mnt/data
    working_dir: /mnt/data
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
